apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: tailoring
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
     containers:
      - name: frontend
        image: tailoring-web-app-image
        ports:
        - containerPort: 3000